/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/student/218549/RosWorkspace4/src/ode_unicycle/srv/SetInitialState.srv
 *
 */


#ifndef ODE_UNICYCLE_MESSAGE_SETINITIALSTATE_H
#define ODE_UNICYCLE_MESSAGE_SETINITIALSTATE_H

#include <ros/service_traits.h>


#include <ode_unicycle/SetInitialStateRequest.h>
#include <ode_unicycle/SetInitialStateResponse.h>


namespace ode_unicycle
{

struct SetInitialState
{

typedef SetInitialStateRequest Request;
typedef SetInitialStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInitialState
} // namespace ode_unicycle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ode_unicycle::SetInitialState > {
  static const char* value()
  {
    return "2cc2c97b3de99a518d38b7026be75633";
  }

  static const char* value(const ::ode_unicycle::SetInitialState&) { return value(); }
};

template<>
struct DataType< ::ode_unicycle::SetInitialState > {
  static const char* value()
  {
    return "ode_unicycle/SetInitialState";
  }

  static const char* value(const ::ode_unicycle::SetInitialState&) { return value(); }
};


// service_traits::MD5Sum< ::ode_unicycle::SetInitialStateRequest> should match 
// service_traits::MD5Sum< ::ode_unicycle::SetInitialState > 
template<>
struct MD5Sum< ::ode_unicycle::SetInitialStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ode_unicycle::SetInitialState >::value();
  }
  static const char* value(const ::ode_unicycle::SetInitialStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ode_unicycle::SetInitialStateRequest> should match 
// service_traits::DataType< ::ode_unicycle::SetInitialState > 
template<>
struct DataType< ::ode_unicycle::SetInitialStateRequest>
{
  static const char* value()
  {
    return DataType< ::ode_unicycle::SetInitialState >::value();
  }
  static const char* value(const ::ode_unicycle::SetInitialStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ode_unicycle::SetInitialStateResponse> should match 
// service_traits::MD5Sum< ::ode_unicycle::SetInitialState > 
template<>
struct MD5Sum< ::ode_unicycle::SetInitialStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ode_unicycle::SetInitialState >::value();
  }
  static const char* value(const ::ode_unicycle::SetInitialStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ode_unicycle::SetInitialStateResponse> should match 
// service_traits::DataType< ::ode_unicycle::SetInitialState > 
template<>
struct DataType< ::ode_unicycle::SetInitialStateResponse>
{
  static const char* value()
  {
    return DataType< ::ode_unicycle::SetInitialState >::value();
  }
  static const char* value(const ::ode_unicycle::SetInitialStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ODE_UNICYCLE_MESSAGE_SETINITIALSTATE_H
